Escape/correct variables for `az login`, fix `sed`

diff --git a/.github/workflows/taskboard-app.yml b/.github/workflows/taskboard-app.yml
--- a/.github/workflows/taskboard-app.yml
+++ b/.github/workflows/taskboard-app.yml
@@ -45,22 +45,23 @@ jobs:
       - uses: actions/checkout@v2
       - name: login az
         run: |
-          az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT
-          az account set -s $SUBSCRIPTION
+          az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"
+          az account set -s "$SUBSCRIPTION"
         env:
           CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
-          TENANT: ${{ secrets.ARM_TENANT }}
+          TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
           SUBSCRIPTION: ${{ secrets.ARM_SUBSCRIPTION_ID }}
       - name: login kubectl
         run: |
           az aks get-credentials -n "aks-taskboard" -g "rg-taskboard"
           kubectl version --short
       - name: patch manifest
-        run: sed "s/christianfosli\/taskboard-app/christianfosli\/taskboard-app:$GITHUB_SHA/" k8s.yml
-      - name: apply
-        run: kubectl apply -f k8s.yml
+        run: sed -i "s|christianfosli/taskboard-app|christianfosli/taskboard-app:$GITHUB_SHA|" k8s.yml
+      - run: kubectl apply -f k8s.yml
       - name: rollout status
         run: |
-          kubectl rollout status deployment taskboard-app || \
-            (printf "\ndeploy failed!, rolling back...\n\n"; kubectl rollout undo deployment taskboard-app; exit 1)
+          kubectl rollout status deployment taskboard-app-deploy || \
+            (printf "\ndeploy failed!, rolling back...\n\n"; \
+             kubectl rollout undo deployment taskboard-app-deploy; \
+             exit 1)
